name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  id-token: write # For OIDC to Azure

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_adf_dev:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'dev/')
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Download ADF artifact
        uses: actions/download-artifact@v4
        with:
          name: adf-arm-template

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          # This requires OIDC to be configured between GitHub and Azure
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ADF content
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP }}
          template: ARMTemplateForFactory.json
          parameters: ARMTemplateParametersForFactory.json

  deploy_adf_staging:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Download ADF artifact
        uses: actions/download-artifact@v4
        with:
          name: adf-arm-template

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          # This requires OIDC to be configured between GitHub and Azure
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ADF content
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP }}
          template: ARMTemplateForFactory.json
          parameters: ARMTemplateParametersForFactory.json

  deploy_adf_production:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    needs: deploy_adf_staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Download ADF artifact
        uses: actions/download-artifact@v4
        with:
          name: adf-arm-template

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          # This requires OIDC to be configured between GitHub and Azure
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ADF content
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP }}
          template: ARMTemplateForFactory.json
          parameters: ARMTemplateParametersForFactory.json