name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/adf/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint with pytest (as a placeholder for a real linter)
        run: |
          source venv/bin/activate
          pytest --version # Using pytest to check installation

      - name: Run Great Expectations Checkpoint
        run: |
          echo "This step would run GX against sample data."
          # In a real CI, you would configure a datasource and run:
          # great_expectations checkpoint run sales

      - name: (Optional) Validate ADF
        uses: Azure/data-factory-validate-action@v1.0.0
        with:
          path: src/adf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Set up Node.js
        if: github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build ADF Artifact
        if: github.event_name == 'push'
        run: |
          npm install -g @microsoft/azure-data-factory-utilities
          npm exec -- adf-publish src/adf --output-path adf-output

      - name: Upload ADF Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: adf-arm-template
          path: adf-output
